spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    #################################
    #   gateway相关配置
    #################################
    gateway:
      ################################
      # 配置允许跨域请求
      ################################
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      #    路由定义
      routes:
        - id: baidu
          uri: http://localhost:6366
          predicates:
            - Path=/user/**

        - id: sina
          uri: https://www.baidu.com/
          predicates:
            - Path=/sina/**


org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
        - /user/login
        - /user/admin
        - /sina
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 3m