spring:
  cloud:
    nacos:
      config:
        server-addr: 175.24.21.25:8848
      discovery:
        server-addr: 175.24.21.25:8848
  application:
    name: user-management
  datasource:
    url: jdbc:mysql://localhost:3306/PythonLearningTools?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678