spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: analysis

  datasource:
    url: jdbc:mysql://localhost:3306/PythonLearningTools?serverTimezone=Asia/shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678